In [27]:
import pandas as pd

file_path = "../dataset/candidates.jsonl"

df = pd.read_json(file_path, lines=True)

print(df.shape)
df.head()

(100000, 8)

,candidate_id,profile,career_history,education,skills,certifications,languages,redrob_signals
0,CAND_0000001,"{'anonymized_name': 'Ira Vora', 'headline': 'B...","[{'company': 'Mindtree', 'title': 'Backend Eng...",[{'institution': 'Lovely Professional Universi...,"[{'name': 'Tailwind', 'proficiency': 'intermed...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 86.9, 'signup_d..."
1,CAND_0000002,"{'anonymized_name': 'Saanvi Sethi', 'headline'...","[{'company': 'Wipro', 'title': 'Operations Man...","[{'institution': 'Local Engineering College', ...","[{'name': 'Project Management', 'proficiency':...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 78.7, 'signup_d..."
2,CAND_0000003,"{'anonymized_name': 'Yash Agarwal', 'headline'...","[{'company': 'TCS', 'title': 'Customer Support...","[{'institution': 'Local Engineering College', ...","[{'name': 'Angular', 'proficiency': 'intermedi...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 31.9, 'signup_d..."
3,CAND_0000004,"{'anonymized_name': 'Anil Bose', 'headline': '...","[{'company': 'Dunder Mifflin', 'title': 'Marke...","[{'institution': 'Local Engineering College', ...","[{'name': 'Node.js', 'proficiency': 'intermedi...","[{'name': 'AWS Certified Cloud Practitioner', ...","[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 28.5, 'signup_d..."
4,CAND_0000005,"{'anonymized_name': 'Aisha Sethi', 'headline':...","[{'company': 'Stark Industries', 'title': 'Acc...","[{'institution': 'Chandigarh University', 'deg...","[{'name': 'SQL', 'proficiency': 'beginner', 'e...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 84.6, 'signup_d..."

In [28]:
import pandas as pd

profile_df = pd.json_normalize(df['profile'])

profile_df.head()

,anonymized_name,headline,summary,location,country,years_of_experience,current_title,current_company,current_company_size,current_industry
0,Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,IT Services
1,Saanvi Sethi,Operations Manager | 12.5+ yrs experience,Professional with 12.5+ years of experience. M...,"Chennai, Tamil Nadu",India,12.5,Operations Manager,Wipro,10001+,IT Services
2,Yash Agarwal,Customer Support | 1.1+ yrs experience,Professional with 1.1+ years of experience. I'...,Austin,USA,1.1,Customer Support,TCS,10001+,IT Services
3,Anil Bose,Marketing Manager | Driving business outcomes,Professional with 3.8+ years of experience. My...,Sydney,Australia,3.8,Marketing Manager,Dunder Mifflin,201-500,Paper Products
4,Aisha Sethi,Accountant | Helping teams scale,Professional with 11.0+ years of experience. I...,"Gurgaon, Haryana",India,11.0,Accountant,Stark Industries,1001-5000,Manufacturing

In [29]:
signals_df = pd.json_normalize(df['redrob_signals'])

signals_df.head()

,profile_completeness_score,signup_date,last_active_date,open_to_work_flag,profile_views_received_30d,applications_submitted_30d,recruiter_response_rate,avg_response_time_hours,connection_count,endorsements_received,...,skill_assessment_scores.Python,skill_assessment_scores.OpenSearch,skill_assessment_scores.BM25,skill_assessment_scores.scikit-learn,skill_assessment_scores.pgvector,skill_assessment_scores.Embeddings,skill_assessment_scores.LlamaIndex,skill_assessment_scores.PyTorch,skill_assessment_scores.Deep Learning,skill_assessment_scores.QLoRA
0,86.9,2025-10-16,2026-05-20,True,23,2,0.34,177.8,356,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,78.7,2025-07-28,2025-11-12,True,7,1,0.29,171.6,179,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,31.9,2024-08-02,2026-03-21,False,1,9,0.46,119.4,19,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28.5,2025-07-21,2026-03-25,False,3,9,0.26,104.1,485,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,84.6,2023-10-07,2025-10-01,True,12,2,0.37,116.7,300,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
profile_df = pd.json_normalize(df['profile'])
signals_df = pd.json_normalize(df['redrob_signals'])

final_df = pd.concat(
    [df[['candidate_id']], profile_df, signals_df],
    axis=1
)

final_df.head()

,candidate_id,anonymized_name,headline,summary,location,country,years_of_experience,current_title,current_company,current_company_size,...,skill_assessment_scores.Python,skill_assessment_scores.OpenSearch,skill_assessment_scores.BM25,skill_assessment_scores.scikit-learn,skill_assessment_scores.pgvector,skill_assessment_scores.Embeddings,skill_assessment_scores.LlamaIndex,skill_assessment_scores.PyTorch,skill_assessment_scores.Deep Learning,skill_assessment_scores.QLoRA
0,CAND_0000001,Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAND_0000002,Saanvi Sethi,Operations Manager | 12.5+ yrs experience,Professional with 12.5+ years of experience. M...,"Chennai, Tamil Nadu",India,12.5,Operations Manager,Wipro,10001+,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CAND_0000003,Yash Agarwal,Customer Support | 1.1+ yrs experience,Professional with 1.1+ years of experience. I'...,Austin,USA,1.1,Customer Support,TCS,10001+,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CAND_0000004,Anil Bose,Marketing Manager | Driving business outcomes,Professional with 3.8+ years of experience. My...,Sydney,Australia,3.8,Marketing Manager,Dunder Mifflin,201-500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CAND_0000005,Aisha Sethi,Accountant | Helping teams scale,Professional with 11.0+ years of experience. I...,"Gurgaon, Haryana",India,11.0,Accountant,Stark Industries,1001-5000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_df.columns.tolist()

['candidate_id',
 'anonymized_name',
 'headline',
 'summary',
 'location',
 'country',
 'years_of_experience',
 'current_title',
 'current_company',
 'current_company_size',
 'current_industry',
 'profile_completeness_score',
 'signup_date',
 'last_active_date',
 'open_to_work_flag',
 'profile_views_received_30d',
 'applications_submitted_30d',
 'recruiter_response_rate',
 'avg_response_time_hours',
 'connection_count',
 'endorsements_received',
 'notice_period_days',
 'preferred_work_mode',
 'willing_to_relocate',
 'github_activity_score',
 'search_appearance_30d',
 'saved_by_recruiters_30d',
 'interview_completion_rate',
 'offer_acceptance_rate',
 'verified_email',
 'verified_phone',
 'linkedin_connected',
 'skill_assessment_scores.NLP',
 'skill_assessment_scores.Image Classification',
 'skill_assessment_scores.Fine-tuning LLMs',
 'skill_assessment_scores.Speech Recognition',
 'expected_salary_range_inr_lpa.min',
 'expected_salary_range_inr_lpa.max',
 'skill_assessment_scores.GANs',
 'skill_assessment_scores.OpenCV',
 'skill_assessment_scores.Prompt Engineering',
 'skill_assessment_scores.Object Detection',
 'skill_assessment_scores.Recommendation Systems',
 'skill_assessment_scores.FAISS',
 'skill_assessment_scores.Weights & Biases',
 'skill_assessment_scores.Forecasting',
 'skill_assessment_scores.LangChain',
 'skill_assessment_scores.YOLO',
 'skill_assessment_scores.PEFT',
 'skill_assessment_scores.Data Science',
 'skill_assessment_scores.MLflow',
 'skill_assessment_scores.Pinecone',
 'skill_assessment_scores.Feature Engineering',
 'skill_assessment_scores.BentoML',
 'skill_assessment_scores.MLOps',
 'skill_assessment_scores.Qdrant',
 'skill_assessment_scores.CNN',
 'skill_assessment_scores.Kubeflow',
 'skill_assessment_scores.Machine Learning',
 'skill_assessment_scores.Reinforcement Learning',
 'skill_assessment_scores.Sentence Transformers',
 'skill_assessment_scores.Haystack',
 'skill_assessment_scores.Hugging Face Transformers',
 'skill_assessment_scores.Semantic Search',
 'skill_assessment_scores.LoRA',
 'skill_assessment_scores.Diffusion Models',
 'skill_assessment_scores.Milvus',
 'skill_assessment_scores.Time Series',
 'skill_assessment_scores.Statistical Modeling',
 'skill_assessment_scores.Elasticsearch',
 'skill_assessment_scores.Information Retrieval',
 'skill_assessment_scores.Vector Search',
 'skill_assessment_scores.Learning to Rank',
 'skill_assessment_scores.ASR',
 'skill_assessment_scores.TensorFlow',
 'skill_assessment_scores.LLMs',
 'skill_assessment_scores.Computer Vision',
 'skill_assessment_scores.TTS',
 'skill_assessment_scores.Weaviate',
 'skill_assessment_scores.RAG',
 'skill_assessment_scores.Python',
 'skill_assessment_scores.OpenSearch',
 'skill_assessment_scores.BM25',
 'skill_assessment_scores.scikit-learn',
 'skill_assessment_scores.pgvector',
 'skill_assessment_scores.Embeddings',
 'skill_assessment_scores.LlamaIndex',
 'skill_assessment_scores.PyTorch',
 'skill_assessment_scores.Deep Learning',
 'skill_assessment_scores.QLoRA']

In [ ]:
final_df['skills_text'] = df['skills'].apply(
    lambda x: ' '.join(skill['name'] for skill in x)
)

In [ ]:
final_df['career_history_text'] = df['career_history'].apply(
    lambda x: ' '.join(
        job['title'] + ' ' + job['description']
        for job in x
    )
)

In [ ]:
final_df[['candidate_id',
          'current_title',
          'years_of_experience',
          'skills_text']].head()

,candidate_id,current_title,years_of_experience,skills_text
0,CAND_0000001,Backend Engineer,6.9,Tailwind NLP Image Classification Fine-tuning ...
1,CAND_0000002,Operations Manager,12.5,Project Management React Photoshop TypeScript ...
2,CAND_0000003,Customer Support,1.1,Angular SEO Excel Accounting Kubernetes Databr...
3,CAND_0000004,Marketing Manager,3.8,Node.js Content Writing Redux Airflow GraphQL ...
4,CAND_0000005,Accountant,11.0,SQL PowerPoint Photoshop Tailwind Apache Flink...

In [ ]:
final_df.head()

,candidate_id,anonymized_name,headline,summary,location,country,years_of_experience,current_title,current_company,current_company_size,...,skill_assessment_scores.Python,skill_assessment_scores.OpenSearch,skill_assessment_scores.BM25,skill_assessment_scores.scikit-learn,skill_assessment_scores.pgvector,skill_assessment_scores.Embeddings,skill_assessment_scores.LlamaIndex,skill_assessment_scores.PyTorch,skill_assessment_scores.Deep Learning,skill_assessment_scores.QLoRA
0,CAND_0000001,Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAND_0000002,Saanvi Sethi,Operations Manager | 12.5+ yrs experience,Professional with 12.5+ years of experience. M...,"Chennai, Tamil Nadu",India,12.5,Operations Manager,Wipro,10001+,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CAND_0000003,Yash Agarwal,Customer Support | 1.1+ yrs experience,Professional with 1.1+ years of experience. I'...,Austin,USA,1.1,Customer Support,TCS,10001+,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CAND_0000004,Anil Bose,Marketing Manager | Driving business outcomes,Professional with 3.8+ years of experience. My...,Sydney,Australia,3.8,Marketing Manager,Dunder Mifflin,201-500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CAND_0000005,Aisha Sethi,Accountant | Helping teams scale,Professional with 11.0+ years of experience. I...,"Gurgaon, Haryana",India,11.0,Accountant,Stark Industries,1001-5000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(final_df.columns.tolist())

['candidate_id', 'anonymized_name', 'headline', 'summary', 'location', 'country', 'years_of_experience', 'current_title', 'current_company', 'current_company_size', 'current_industry', 'profile_completeness_score', 'signup_date', 'last_active_date', 'open_to_work_flag', 'profile_views_received_30d', 'applications_submitted_30d', 'recruiter_response_rate', 'avg_response_time_hours', 'connection_count', 'endorsements_received', 'notice_period_days', 'preferred_work_mode', 'willing_to_relocate', 'github_activity_score', 'search_appearance_30d', 'saved_by_recruiters_30d', 'interview_completion_rate', 'offer_acceptance_rate', 'verified_email', 'verified_phone', 'linkedin_connected', 'skill_assessment_scores.NLP', 'skill_assessment_scores.Image Classification', 'skill_assessment_scores.Fine-tuning LLMs', 'skill_assessment_scores.Speech Recognition', 'expected_salary_range_inr_lpa.min', 'expected_salary_range_inr_lpa.max', 'skill_assessment_scores.GANs', 'skill_assessment_scores.OpenCV', 'skill_assessment_scores.Prompt Engineering', 'skill_assessment_scores.Object Detection', 'skill_assessment_scores.Recommendation Systems', 'skill_assessment_scores.FAISS', 'skill_assessment_scores.Weights & Biases', 'skill_assessment_scores.Forecasting', 'skill_assessment_scores.LangChain', 'skill_assessment_scores.YOLO', 'skill_assessment_scores.PEFT', 'skill_assessment_scores.Data Science', 'skill_assessment_scores.MLflow', 'skill_assessment_scores.Pinecone', 'skill_assessment_scores.Feature Engineering', 'skill_assessment_scores.BentoML', 'skill_assessment_scores.MLOps', 'skill_assessment_scores.Qdrant', 'skill_assessment_scores.CNN', 'skill_assessment_scores.Kubeflow', 'skill_assessment_scores.Machine Learning', 'skill_assessment_scores.Reinforcement Learning', 'skill_assessment_scores.Sentence Transformers', 'skill_assessment_scores.Haystack', 'skill_assessment_scores.Hugging Face Transformers', 'skill_assessment_scores.Semantic Search', 'skill_assessment_scores.LoRA', 'skill_assessment_scores.Diffusion Models', 'skill_assessment_scores.Milvus', 'skill_assessment_scores.Time Series', 'skill_assessment_scores.Statistical Modeling', 'skill_assessment_scores.Elasticsearch', 'skill_assessment_scores.Information Retrieval', 'skill_assessment_scores.Vector Search', 'skill_assessment_scores.Learning to Rank', 'skill_assessment_scores.ASR', 'skill_assessment_scores.TensorFlow', 'skill_assessment_scores.LLMs', 'skill_assessment_scores.Computer Vision', 'skill_assessment_scores.TTS', 'skill_assessment_scores.Weaviate', 'skill_assessment_scores.RAG', 'skill_assessment_scores.Python', 'skill_assessment_scores.OpenSearch', 'skill_assessment_scores.BM25', 'skill_assessment_scores.scikit-learn', 'skill_assessment_scores.pgvector', 'skill_assessment_scores.Embeddings', 'skill_assessment_scores.LlamaIndex', 'skill_assessment_scores.PyTorch', 'skill_assessment_scores.Deep Learning', 'skill_assessment_scores.QLoRA']

In [ ]:
final_df.columns

Index(['candidate_id', 'anonymized_name', 'headline', 'summary', 'location',
       'country', 'years_of_experience', 'current_title', 'current_company',
       'current_company_size', 'current_industry',
       'profile_completeness_score', 'signup_date', 'last_active_date',
       'open_to_work_flag', 'profile_views_received_30d',
       'applications_submitted_30d', 'recruiter_response_rate',
       'avg_response_time_hours', 'connection_count', 'endorsements_received',
       'notice_period_days', 'preferred_work_mode', 'willing_to_relocate',
       'github_activity_score', 'search_appearance_30d',
       'saved_by_recruiters_30d', 'interview_completion_rate',
       'offer_acceptance_rate', 'verified_email', 'verified_phone',
       'linkedin_connected', 'skill_assessment_scores.NLP',
       'skill_assessment_scores.Image Classification',
       'skill_assessment_scores.Fine-tuning LLMs',
       'skill_assessment_scores.Speech Recognition',
       'expected_salary_range_inr_lpa.min',
       'expected_salary_range_inr_lpa.max', 'skill_assessment_scores.GANs',
       'skill_assessment_scores.OpenCV',
       'skill_assessment_scores.Prompt Engineering',
       'skill_assessment_scores.Object Detection',
       'skill_assessment_scores.Recommendation Systems',
       'skill_assessment_scores.FAISS',
       'skill_assessment_scores.Weights & Biases',
       'skill_assessment_scores.Forecasting',
       'skill_assessment_scores.LangChain', 'skill_assessment_scores.YOLO',
       'skill_assessment_scores.PEFT', 'skill_assessment_scores.Data Science',
       'skill_assessment_scores.MLflow', 'skill_assessment_scores.Pinecone',
       'skill_assessment_scores.Feature Engineering',
       'skill_assessment_scores.BentoML', 'skill_assessment_scores.MLOps',
       'skill_assessment_scores.Qdrant', 'skill_assessment_scores.CNN',
       'skill_assessment_scores.Kubeflow',
       'skill_assessment_scores.Machine Learning',
       'skill_assessment_scores.Reinforcement Learning',
       'skill_assessment_scores.Sentence Transformers',
       'skill_assessment_scores.Haystack',
       'skill_assessment_scores.Hugging Face Transformers',
       'skill_assessment_scores.Semantic Search',
       'skill_assessment_scores.LoRA',
       'skill_assessment_scores.Diffusion Models',
       'skill_assessment_scores.Milvus', 'skill_assessment_scores.Time Series',
       'skill_assessment_scores.Statistical Modeling',
       'skill_assessment_scores.Elasticsearch',
       'skill_assessment_scores.Information Retrieval',
       'skill_assessment_scores.Vector Search',
       'skill_assessment_scores.Learning to Rank',
       'skill_assessment_scores.ASR', 'skill_assessment_scores.TensorFlow',
       'skill_assessment_scores.LLMs',
       'skill_assessment_scores.Computer Vision',
       'skill_assessment_scores.TTS', 'skill_assessment_scores.Weaviate',
       'skill_assessment_scores.RAG', 'skill_assessment_scores.Python',
       'skill_assessment_scores.OpenSearch', 'skill_assessment_scores.BM25',
       'skill_assessment_scores.scikit-learn',
       'skill_assessment_scores.pgvector',
       'skill_assessment_scores.Embeddings',
       'skill_assessment_scores.LlamaIndex', 'skill_assessment_scores.PyTorch',
       'skill_assessment_scores.Deep Learning',
       'skill_assessment_scores.QLoRA'],
      dtype='object')

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 90 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   candidate_id                                       100000 non-null  object
 1   anonymized_name                                    100000 non-null  object
 2   headline                                           100000 non-null  object
 3   summary                                            100000 non-null  object
 4   location                                           100000 non-null  object
 5   country                                            100000 non-null  object
 6   years_of_experience                                100000 non-null  float64
 7   current_title                                      100000 non-null  object
 8   current_company                                    100000 non-null  object
 9   current_company_size                               100000 non-null  object
 10  current_industry                                   100000 non-null  object
 11  profile_completeness_score                         100000 non-null  float64
 12  signup_date                                        100000 non-null  object
 13  last_active_date                                   100000 non-null  object
 14  open_to_work_flag                                  100000 non-null  bool
 15  profile_views_received_30d                         100000 non-null  int64
 16  applications_submitted_30d                         100000 non-null  int64
 17  recruiter_response_rate                            100000 non-null  float64
 18  avg_response_time_hours                            100000 non-null  float64
 19  connection_count                                   100000 non-null  int64
 20  endorsements_received                              100000 non-null  int64
 21  notice_period_days                                 100000 non-null  int64
 22  preferred_work_mode                                100000 non-null  object
 23  willing_to_relocate                                100000 non-null  bool
 24  github_activity_score                              100000 non-null  float64
 25  search_appearance_30d                              100000 non-null  int64
 26  saved_by_recruiters_30d                            100000 non-null  int64
 27  interview_completion_rate                          100000 non-null  float64
 28  offer_acceptance_rate                              100000 non-null  float64
 29  verified_email                                     100000 non-null  bool
 30  verified_phone                                     100000 non-null  bool
 31  linkedin_connected                                 100000 non-null  bool
 32  skill_assessment_scores.NLP                        306 non-null     float64
 33  skill_assessment_scores.Image Classification       1120 non-null    float64
 34  skill_assessment_scores.Fine-tuning LLMs           282 non-null     float64
 35  skill_assessment_scores.Speech Recognition         1159 non-null    float64
 36  expected_salary_range_inr_lpa.min                  100000 non-null  float64
 37  expected_salary_range_inr_lpa.max                  100000 non-null  float64
 38  skill_assessment_scores.GANs                       1122 non-null    float64
 39  skill_assessment_scores.OpenCV                     1155 non-null    float64
 40  skill_assessment_scores.Prompt Engineering         312 non-null     float64
 41  skill_assessment_scores.Object Detection           1145 non-null    float64
 42  skill_assessment_scores.Recommendation Systems     325 non-null     float64
 43  skill_assessment_scores.FAISS                      303 non-null     float64
 44  skill_assessment_scores.Weights & Biases           1173 non-null    float64
 45  skill_assessment_scores.Forecasting                1167 non-null    float64
 46  skill_assessment_scores.LangChain                  295 non-null     float64
 47  skill_assessment_scores.YOLO                       1195 non-null    float64
 48  skill_assessment_scores.PEFT                       341 non-null     float64
 49  skill_assessment_scores.Data Science               1147 non-null    float64
 50  skill_assessment_scores.MLflow                     1085 non-null    float64
 51  skill_assessment_scores.Pinecone                   325 non-null     float64
 52  skill_assessment_scores.Feature Engineering        1174 non-null    float64
 53  skill_assessment_scores.BentoML                    1157 non-null    float64
 54  skill_assessment_scores.MLOps                      1159 non-null    float64
 55  skill_assessment_scores.Qdrant                     336 non-null     float64
 56  skill_assessment_scores.CNN                        1174 non-null    float64
 57  skill_assessment_scores.Kubeflow                   1105 non-null    float64
 58  skill_assessment_scores.Machine Learning           335 non-null     float64
 59  skill_assessment_scores.Reinforcement Learning     1124 non-null    float64
 60  skill_assessment_scores.Sentence Transformers      328 non-null     float64
 61  skill_assessment_scores.Haystack                   314 non-null     float64
 62  skill_assessment_scores.Hugging Face Transformers  319 non-null     float64
 63  skill_assessment_scores.Semantic Search            301 non-null     float64
 64  skill_assessment_scores.LoRA                       320 non-null     float64
 65  skill_assessment_scores.Diffusion Models           1133 non-null    float64
 66  skill_assessment_scores.Milvus                     340 non-null     float64
 67  skill_assessment_scores.Time Series                1111 non-null    float64
 68  skill_assessment_scores.Statistical Modeling       1088 non-null    float64
 69  skill_assessment_scores.Elasticsearch              285 non-null     float64
 70  skill_assessment_scores.Information Retrieval      343 non-null     float64
 71  skill_assessment_scores.Vector Search              326 non-null     float64
 72  skill_assessment_scores.Learning to Rank           327 non-null     float64
 73  skill_assessment_scores.ASR                        1124 non-null    float64
 74  skill_assessment_scores.TensorFlow                 326 non-null     float64
 75  skill_assessment_scores.LLMs                       323 non-null     float64
 76  skill_assessment_scores.Computer Vision            1111 non-null    float64
 77  skill_assessment_scores.TTS                        1140 non-null    float64
 78  skill_assessment_scores.Weaviate                   321 non-null     float64
 79  skill_assessment_scores.RAG                        326 non-null     float64
 80  skill_assessment_scores.Python                     312 non-null     float64
 81  skill_assessment_scores.OpenSearch                 319 non-null     float64
 82  skill_assessment_scores.BM25                       309 non-null     float64
 83  skill_assessment_scores.scikit-learn               317 non-null     float64
 84  skill_assessment_scores.pgvector                   340 non-null     float64
 85  skill_assessment_scores.Embeddings                 327 non-null     float64
 86  skill_assessment_scores.LlamaIndex                 291 non-null     float64
 87  skill_assessment_scores.PyTorch                    340 non-null     float64
 88  skill_assessment_scores.Deep Learning              284 non-null     float64
 89  skill_assessment_scores.QLoRA                      329 non-null     float64
dtypes: bool(5), float64(65), int64(7), object(13)
memory usage: 65.3+ MB

In [36]:
drop_cols = [
    'verified_email',
    'verified_phone'
]
final_df = final_df.drop(columns=drop_cols)

In [37]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 88 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   candidate_id                                       100000 non-null  object
 1   anonymized_name                                    100000 non-null  object
 2   headline                                           100000 non-null  object
 3   summary                                            100000 non-null  object
 4   location                                           100000 non-null  object
 5   country                                            100000 non-null  object
 6   years_of_experience                                100000 non-null  float64
 7   current_title                                      100000 non-null  object
 8   current_company                                    100000 non-null  object
 9   current_company_size                               100000 non-null  object
 10  current_industry                                   100000 non-null  object
 11  profile_completeness_score                         100000 non-null  float64
 12  signup_date                                        100000 non-null  object
 13  last_active_date                                   100000 non-null  object
 14  open_to_work_flag                                  100000 non-null  bool
 15  profile_views_received_30d                         100000 non-null  int64
 16  applications_submitted_30d                         100000 non-null  int64
 17  recruiter_response_rate                            100000 non-null  float64
 18  avg_response_time_hours                            100000 non-null  float64
 19  connection_count                                   100000 non-null  int64
 20  endorsements_received                              100000 non-null  int64
 21  notice_period_days                                 100000 non-null  int64
 22  preferred_work_mode                                100000 non-null  object
 23  willing_to_relocate                                100000 non-null  bool
 24  github_activity_score                              100000 non-null  float64
 25  search_appearance_30d                              100000 non-null  int64
 26  saved_by_recruiters_30d                            100000 non-null  int64
 27  interview_completion_rate                          100000 non-null  float64
 28  offer_acceptance_rate                              100000 non-null  float64
 29  linkedin_connected                                 100000 non-null  bool
 30  skill_assessment_scores.NLP                        306 non-null     float64
 31  skill_assessment_scores.Image Classification       1120 non-null    float64
 32  skill_assessment_scores.Fine-tuning LLMs           282 non-null     float64
 33  skill_assessment_scores.Speech Recognition         1159 non-null    float64
 34  expected_salary_range_inr_lpa.min                  100000 non-null  float64
 35  expected_salary_range_inr_lpa.max                  100000 non-null  float64
 36  skill_assessment_scores.GANs                       1122 non-null    float64
 37  skill_assessment_scores.OpenCV                     1155 non-null    float64
 38  skill_assessment_scores.Prompt Engineering         312 non-null     float64
 39  skill_assessment_scores.Object Detection           1145 non-null    float64
 40  skill_assessment_scores.Recommendation Systems     325 non-null     float64
 41  skill_assessment_scores.FAISS                      303 non-null     float64
 42  skill_assessment_scores.Weights & Biases           1173 non-null    float64
 43  skill_assessment_scores.Forecasting                1167 non-null    float64
 44  skill_assessment_scores.LangChain                  295 non-null     float64
 45  skill_assessment_scores.YOLO                       1195 non-null    float64
 46  skill_assessment_scores.PEFT                       341 non-null     float64
 47  skill_assessment_scores.Data Science               1147 non-null    float64
 48  skill_assessment_scores.MLflow                     1085 non-null    float64
 49  skill_assessment_scores.Pinecone                   325 non-null     float64
 50  skill_assessment_scores.Feature Engineering        1174 non-null    float64
 51  skill_assessment_scores.BentoML                    1157 non-null    float64
 52  skill_assessment_scores.MLOps                      1159 non-null    float64
 53  skill_assessment_scores.Qdrant                     336 non-null     float64
 54  skill_assessment_scores.CNN                        1174 non-null    float64
 55  skill_assessment_scores.Kubeflow                   1105 non-null    float64
 56  skill_assessment_scores.Machine Learning           335 non-null     float64
 57  skill_assessment_scores.Reinforcement Learning     1124 non-null    float64
 58  skill_assessment_scores.Sentence Transformers      328 non-null     float64
 59  skill_assessment_scores.Haystack                   314 non-null     float64
 60  skill_assessment_scores.Hugging Face Transformers  319 non-null     float64
 61  skill_assessment_scores.Semantic Search            301 non-null     float64
 62  skill_assessment_scores.LoRA                       320 non-null     float64
 63  skill_assessment_scores.Diffusion Models           1133 non-null    float64
 64  skill_assessment_scores.Milvus                     340 non-null     float64
 65  skill_assessment_scores.Time Series                1111 non-null    float64
 66  skill_assessment_scores.Statistical Modeling       1088 non-null    float64
 67  skill_assessment_scores.Elasticsearch              285 non-null     float64
 68  skill_assessment_scores.Information Retrieval      343 non-null     float64
 69  skill_assessment_scores.Vector Search              326 non-null     float64
 70  skill_assessment_scores.Learning to Rank           327 non-null     float64
 71  skill_assessment_scores.ASR                        1124 non-null    float64
 72  skill_assessment_scores.TensorFlow                 326 non-null     float64
 73  skill_assessment_scores.LLMs                       323 non-null     float64
 74  skill_assessment_scores.Computer Vision            1111 non-null    float64
 75  skill_assessment_scores.TTS                        1140 non-null    float64
 76  skill_assessment_scores.Weaviate                   321 non-null     float64
 77  skill_assessment_scores.RAG                        326 non-null     float64
 78  skill_assessment_scores.Python                     312 non-null     float64
 79  skill_assessment_scores.OpenSearch                 319 non-null     float64
 80  skill_assessment_scores.BM25                       309 non-null     float64
 81  skill_assessment_scores.scikit-learn               317 non-null     float64
 82  skill_assessment_scores.pgvector                   340 non-null     float64
 83  skill_assessment_scores.Embeddings                 327 non-null     float64
 84  skill_assessment_scores.LlamaIndex                 291 non-null     float64
 85  skill_assessment_scores.PyTorch                    340 non-null     float64
 86  skill_assessment_scores.Deep Learning              284 non-null     float64
 87  skill_assessment_scores.QLoRA                      329 non-null     float64
dtypes: bool(3), float64(65), int64(7), object(13)
memory usage: 65.1+ MB

In [40]:
final_df.isnull().count()

candidate_id                             100000
anonymized_name                          100000
headline                                 100000
summary                                  100000
location                                 100000
                                          ...
skill_assessment_scores.Embeddings       100000
skill_assessment_scores.LlamaIndex       100000
skill_assessment_scores.PyTorch          100000
skill_assessment_scores.Deep Learning    100000
skill_assessment_scores.QLoRA            100000
Length: 88, dtype: int64

In [42]:
null_counts = final_df.isnull().sum()
print(null_counts[null_counts > 0])

skill_assessment_scores.NLP                          99694
skill_assessment_scores.Image Classification         98880
skill_assessment_scores.Fine-tuning LLMs             99718
skill_assessment_scores.Speech Recognition           98841
skill_assessment_scores.GANs                         98878
skill_assessment_scores.OpenCV                       98845
skill_assessment_scores.Prompt Engineering           99688
skill_assessment_scores.Object Detection             98855
skill_assessment_scores.Recommendation Systems       99675
skill_assessment_scores.FAISS                        99697
skill_assessment_scores.Weights & Biases             98827
skill_assessment_scores.Forecasting                  98833
skill_assessment_scores.LangChain                    99705
skill_assessment_scores.YOLO                         98805
skill_assessment_scores.PEFT                         99659
skill_assessment_scores.Data Science                 98853
skill_assessment_scores.MLflow                       98915
skill_assessment_scores.Pinecone                     99675
skill_assessment_scores.Feature Engineering          98826
skill_assessment_scores.BentoML                      98843
skill_assessment_scores.MLOps                        98841
skill_assessment_scores.Qdrant                       99664
skill_assessment_scores.CNN                          98826
skill_assessment_scores.Kubeflow                     98895
skill_assessment_scores.Machine Learning             99665
skill_assessment_scores.Reinforcement Learning       98876
skill_assessment_scores.Sentence Transformers        99672
skill_assessment_scores.Haystack                     99686
skill_assessment_scores.Hugging Face Transformers    99681
skill_assessment_scores.Semantic Search              99699
skill_assessment_scores.LoRA                         99680
skill_assessment_scores.Diffusion Models             98867
skill_assessment_scores.Milvus                       99660
skill_assessment_scores.Time Series                  98889
skill_assessment_scores.Statistical Modeling         98912
skill_assessment_scores.Elasticsearch                99715
skill_assessment_scores.Information Retrieval        99657
skill_assessment_scores.Vector Search                99674
skill_assessment_scores.Learning to Rank             99673
skill_assessment_scores.ASR                          98876
skill_assessment_scores.TensorFlow                   99674
skill_assessment_scores.LLMs                         99677
skill_assessment_scores.Computer Vision              98889
skill_assessment_scores.TTS                          98860
skill_assessment_scores.Weaviate                     99679
skill_assessment_scores.RAG                          99674
skill_assessment_scores.Python                       99688
skill_assessment_scores.OpenSearch                   99681
skill_assessment_scores.BM25                         99691
skill_assessment_scores.scikit-learn                 99683
skill_assessment_scores.pgvector                     99660
skill_assessment_scores.Embeddings                   99673
skill_assessment_scores.LlamaIndex                   99709
skill_assessment_scores.PyTorch                      99660
skill_assessment_scores.Deep Learning                99716
skill_assessment_scores.QLoRA                        99671
dtype: int64

In [ ]:
import pandas as pd

file_path = "../dataset/candidates.jsonl"

df = pd.read_json(file_path, lines=True)

print(df.shape)
df.head()

(100000, 8)

,candidate_id,profile,career_history,education,skills,certifications,languages,redrob_signals
0,CAND_0000001,"{'anonymized_name': 'Ira Vora', 'headline': 'B...","[{'company': 'Mindtree', 'title': 'Backend Eng...",[{'institution': 'Lovely Professional Universi...,"[{'name': 'Tailwind', 'proficiency': 'intermed...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 86.9, 'signup_d..."
1,CAND_0000002,"{'anonymized_name': 'Saanvi Sethi', 'headline'...","[{'company': 'Wipro', 'title': 'Operations Man...","[{'institution': 'Local Engineering College', ...","[{'name': 'Project Management', 'proficiency':...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 78.7, 'signup_d..."
2,CAND_0000003,"{'anonymized_name': 'Yash Agarwal', 'headline'...","[{'company': 'TCS', 'title': 'Customer Support...","[{'institution': 'Local Engineering College', ...","[{'name': 'Angular', 'proficiency': 'intermedi...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 31.9, 'signup_d..."
3,CAND_0000004,"{'anonymized_name': 'Anil Bose', 'headline': '...","[{'company': 'Dunder Mifflin', 'title': 'Marke...","[{'institution': 'Local Engineering College', ...","[{'name': 'Node.js', 'proficiency': 'intermedi...","[{'name': 'AWS Certified Cloud Practitioner', ...","[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 28.5, 'signup_d..."
4,CAND_0000005,"{'anonymized_name': 'Aisha Sethi', 'headline':...","[{'company': 'Stark Industries', 'title': 'Acc...","[{'institution': 'Chandigarh University', 'deg...","[{'name': 'SQL', 'proficiency': 'beginner', 'e...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 84.6, 'signup_d..."

In [ ]:
final_df.to_csv("dataset/final_df_processed.csv", index=False)

In [43]:
import os
print(os.getcwd())

/Users/vaishnavikunte/Documents/AI_Recruiter/notebooks

In [44]:
import os

final_df.to_csv("final_df_processed.csv", index=False)

print(os.path.exists("final_df_processed.csv"))

True

In [ ]:
import pandas as pd

file_path = "../dataset/candidates.jsonl"

df = pd.read_json(file_path, lines=True)

print(df.shape)
df.head()

(100000, 8)

,candidate_id,profile,career_history,education,skills,certifications,languages,redrob_signals
0,CAND_0000001,"{'anonymized_name': 'Ira Vora', 'headline': 'B...","[{'company': 'Mindtree', 'title': 'Backend Eng...",[{'institution': 'Lovely Professional Universi...,"[{'name': 'Tailwind', 'proficiency': 'intermed...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 86.9, 'signup_d..."
1,CAND_0000002,"{'anonymized_name': 'Saanvi Sethi', 'headline'...","[{'company': 'Wipro', 'title': 'Operations Man...","[{'institution': 'Local Engineering College', ...","[{'name': 'Project Management', 'proficiency':...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 78.7, 'signup_d..."
2,CAND_0000003,"{'anonymized_name': 'Yash Agarwal', 'headline'...","[{'company': 'TCS', 'title': 'Customer Support...","[{'institution': 'Local Engineering College', ...","[{'name': 'Angular', 'proficiency': 'intermedi...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 31.9, 'signup_d..."
3,CAND_0000004,"{'anonymized_name': 'Anil Bose', 'headline': '...","[{'company': 'Dunder Mifflin', 'title': 'Marke...","[{'institution': 'Local Engineering College', ...","[{'name': 'Node.js', 'proficiency': 'intermedi...","[{'name': 'AWS Certified Cloud Practitioner', ...","[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 28.5, 'signup_d..."
4,CAND_0000005,"{'anonymized_name': 'Aisha Sethi', 'headline':...","[{'company': 'Stark Industries', 'title': 'Acc...","[{'institution': 'Chandigarh University', 'deg...","[{'name': 'SQL', 'proficiency': 'beginner', 'e...",[],"[{'language': 'English', 'proficiency': 'profe...","{'profile_completeness_score': 84.6, 'signup_d..."